name: Continuous Integration
on:
    pull_request:
    push:
        branches:
            - 'master'

jobs:
    ci:
        name: Continuous Integration
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the branch
              uses: actions/checkout@v3

            - name: Set up NodeJS
              uses: actions/setup-node@v3
              with:
                  node-version: '18'

            - name: Install dependencies
              run: npm i

            - name: Run formatter
              run: npm run check-pretty

            - name: Run linter
              run: npm run lint

            - name: Run tests
              run: npm test
